version: '3.5'

services:

  dl4se-db:
    container_name: dl4se-db
    image: postgres:14.2-alpine
    volumes:
      - data:/var/lib/postgresql/data
    networks: [ default ]
    environment:
      TZ: UTC
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  dl4se-liquibase:
    container_name: dl4se-liquibase
    image: liquibase/liquibase:4.9
    command: --username=${DATABASE_USER} --password=${DATABASE_PASS} --url=jdbc:postgresql://dl4se-db:${DATABASE_PORT}/${DATABASE_NAME} --changeLogFile=changelog.xml --hub-mode=off update
    volumes:
      - ../liquibase/changelog.xml:/liquibase/changelog.xml
      - ../liquibase/scripts/:/liquibase/scripts/
    networks: [ default ]
    depends_on:
      dl4se-db:
        condition: service_healthy

  dl4se-crawler:
    container_name: dl4se-crawler
    image: dl4se/dl4se-crawler:latest
    build:
      context: ../
      dockerfile: deployment/crawler/Dockerfile
    networks: [ default ]
    environment:
      LIQUIBASE_HOST: dl4se-liquibase
      DATABASE_HOST: dl4se-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      CODE_SEARCH_URL: http://gym.si.usi.ch:48001/api/r/search
    volumes:
      - logs-crawler:/logs
    depends_on:
      dl4se-liquibase:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  data:
    name: dl4se-data
  logs-crawler:
    name: dl4se-logs-crawler

networks:
  default:
    name: dl4se-network
