version: '3.5'

services:

  dl4se-db:
    container_name: dl4se-db
    image: postgres:14.2-alpine
    networks: [dl4se-network]
    environment:
      TZ: UTC
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  dl4se-liquibase:
    container_name: dl4se-liquibase
    image: liquibase/liquibase:4.9
    command: --url=jdbc:postgresql://dl4se-db:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USER}&password=${DATABASE_PASS} --changeLogFile=changelog.xml --hub-mode=off update
    volumes:
      - ../liquibase/changelog.xml:/liquibase/changelog.xml
      - ../liquibase/scripts/:/liquibase/scripts/
    networks: [dl4se-network]
    depends_on: [dl4se-db]

  dl4se-crawler:
    container_name: dl4se-crawler
    image: dl4se/dl4se-crawler
    build:
      context: ../
      dockerfile: deployment/crawler/Dockerfile
    networks: [dl4se-network]
    environment:
      DATABASE_HOST: dl4se-db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      CODE_SEARCH_URL: http://gym.si.usi.ch:48001/api/r/search
    ports:
      - ${CRAWLER_PORT}:${CRAWLER_PORT}
    depends_on: [dl4se-liquibase]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  dl4se-network:
