name: Maven Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main beanch
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Included Libraries
        run: >
          mvn
          install:install-file
          -Dfile="./dl4se-src2abs/lib/javalexer.jar"
          -DgroupId="edu.wm.cs"
          -DartifactId="javalexer"
          -Dversion="1"
          -Dpackaging="jar"
      - name: Build with Maven
        run: >
          mvn
          --batch-mode
          --update-snapshots
          --no-transfer-progress
          package
